### ISSUE TITLE
Dirvish organisation

### ISSUE THREAD

**Issue by mjbnz** [keachi/dirvish-rpm#1]
Hi,

can you please contact me regarding the dirvish github organisation you own. You can email me at mike@dirvish.org

Thanks,
Mike.

**Comment by keachi** [comment]
Hi Mike,
I'm just a part of this organisation, but I'm not the owner of this group. This organisation and the project was launched after the [mailing list](https://lists.dirvish.org/listinfo/dirvish) thread [#3122](https://lists.dirvish.org/pipermail/dirvish/2018-May/thread.html#3122). Please contact the owner of the organisation - see [appropriate email](https://lists.dirvish.org/pipermail/dirvish/2018-May/003125.html).
Thanks,
keachi

**Comment by mjbnz** [comment]
Heya,

Thanks for the reply - GitHub is showing me that you're the only member of the organisation for some reason - I'd actually missed your email to that thread requesting access. I'll follow up there.

Cheers,
Mike.

(I should have opened this on the actual dirvish repo, not here, my apologies - anyway, I'll close it now).
